package com.lojavirtuall.model;
// Generated 25 de nov. de 2022 01:10:00 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PedidoId generated by hbm2java
 */
@Embeddable
public class PedidoId implements java.io.Serializable {

	private int clienteId;
	private int cursoId;

	public PedidoId() {
	}

	public PedidoId(int clienteId, int cursoId) {
		this.clienteId = clienteId;
		this.cursoId = cursoId;
	}

	@Column(name = "cliente_id", nullable = false)
	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "curso_id", nullable = false)
	public int getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(int cursoId) {
		this.cursoId = cursoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedidoId))
			return false;
		PedidoId castOther = (PedidoId) other;

		return (this.getClienteId() == castOther.getClienteId()) && (this.getCursoId() == castOther.getCursoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClienteId();
		result = 37 * result + this.getCursoId();
		return result;
	}

}
