package com.curso4.unidade5.model;
// Generated 7 de nov. de 2022 23:22:36 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClienteHasCurso generated by hbm2java
 */
@Entity
@Table(name = "Cliente_has_Curso", catalog = "lojavirtual")
public class ClienteHasCurso implements java.io.Serializable {

	private ClienteHasCursoId id;

	public ClienteHasCurso() {
	}

	public ClienteHasCurso(ClienteHasCursoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clienteId", column = @Column(name = "cliente_id", nullable = false)),
			@AttributeOverride(name = "cursoId", column = @Column(name = "curso_id", nullable = false)),
			@AttributeOverride(name = "dataVenda", column = @Column(name = "data_venda", nullable = false, length = 19)) })
	public ClienteHasCursoId getId() {
		return this.id;
	}

	public void setId(ClienteHasCursoId id) {
		this.id = id;
	}

}
