package com.curso4.unidade5.model;
// Generated 7 de nov. de 2022 23:22:36 by Hibernate Tools 4.3.6.Final

import java.time.LocalDate;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteHasCursoId generated by hbm2java
 */
@Embeddable
public class ClienteHasCursoId implements java.io.Serializable {

	private int clienteId;
	private int cursoId;
	private Date dataVenda;

	public ClienteHasCursoId() {
	}


    public ClienteHasCursoId(int clienteId, int cursoId) {
		this.clienteId = clienteId;
		this.cursoId = cursoId;
		this.dataVenda = java.sql.Date.valueOf(LocalDate.now());
	}

	public ClienteHasCursoId(int clienteId, int cursoId, Date dataVenda) {
		this.clienteId = clienteId;
		this.cursoId = cursoId;
		this.dataVenda = dataVenda;
	}

	@Column(name = "cliente_id", nullable = false)
	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "curso_id", nullable = false)
	public int getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(int cursoId) {
		this.cursoId = cursoId;
	}

	@Column(name = "data_venda", nullable = false, length = 19)
	public Date getDataVenda() {
		return this.dataVenda;
	}

	public void setDataVenda(Date dataVenda) {
		this.dataVenda = dataVenda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteHasCursoId))
			return false;
		ClienteHasCursoId castOther = (ClienteHasCursoId) other;

		return (this.getClienteId() == castOther.getClienteId())
				&& (this.getCursoId() == castOther.getCursoId())
				&& ((this.getDataVenda() == castOther.getDataVenda())
						|| (this.getDataVenda() != null
								&& castOther.getDataVenda() != null
								&& this.getDataVenda()
										.equals(castOther.getDataVenda())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClienteId();
		result = 37 * result + this.getCursoId();
		result = 37 * result
				+ (getDataVenda() == null ? 0 : this.getDataVenda().hashCode());
		return result;
	}

}
