package com.teste;
// Generated 25 de nov. de 2022 01:10:00 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "Cliente", uniqueConstraints = @UniqueConstraint(columnNames = "cliente_email"))
public class Cliente implements java.io.Serializable {

	private Integer clienteId;
	private String clienteNome;
	private String clienteSobrenome;
	private String clienteTelefone;
	private String clienteCpf;
	private String clienteEmail;
	private String clienteSenha;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}

	public Cliente(String clienteEmail, String clienteSenha) {
		this.clienteEmail = clienteEmail;
		this.clienteSenha = clienteSenha;
	}

	public Cliente(String clienteNome, String clienteSobrenome, String clienteTelefone, String clienteCpf,
			String clienteEmail, String clienteSenha, Set<Pedido> pedidos) {
		this.clienteNome = clienteNome;
		this.clienteSobrenome = clienteSobrenome;
		this.clienteTelefone = clienteTelefone;
		this.clienteCpf = clienteCpf;
		this.clienteEmail = clienteEmail;
		this.clienteSenha = clienteSenha;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cliente_id", unique = true, nullable = false)
	public Integer getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(Integer clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "cliente_nome", length = 20)
	public String getClienteNome() {
		return this.clienteNome;
	}

	public void setClienteNome(String clienteNome) {
		this.clienteNome = clienteNome;
	}

	@Column(name = "cliente_sobrenome", length = 40)
	public String getClienteSobrenome() {
		return this.clienteSobrenome;
	}

	public void setClienteSobrenome(String clienteSobrenome) {
		this.clienteSobrenome = clienteSobrenome;
	}

	@Column(name = "cliente_telefone", length = 16)
	public String getClienteTelefone() {
		return this.clienteTelefone;
	}

	public void setClienteTelefone(String clienteTelefone) {
		this.clienteTelefone = clienteTelefone;
	}

	@Column(name = "cliente_cpf", length = 14)
	public String getClienteCpf() {
		return this.clienteCpf;
	}

	public void setClienteCpf(String clienteCpf) {
		this.clienteCpf = clienteCpf;
	}

	@Column(name = "cliente_email", unique = true, nullable = false, length = 30)
	public String getClienteEmail() {
		return this.clienteEmail;
	}

	public void setClienteEmail(String clienteEmail) {
		this.clienteEmail = clienteEmail;
	}

	@Column(name = "cliente_senha", nullable = false, length = 30)
	public String getClienteSenha() {
		return this.clienteSenha;
	}

	public void setClienteSenha(String clienteSenha) {
		this.clienteSenha = clienteSenha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
