package com.teste;
// Generated 25 de nov. de 2022 01:10:00 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "Pedido")
public class Pedido implements java.io.Serializable {

	private PedidoId id;
	private Cliente cliente;
	private Curso curso;
	private Date pedidoData;

	public Pedido() {
	}

	public Pedido(PedidoId id, Cliente cliente, Curso curso, Date pedidoData) {
		this.id = id;
		this.cliente = cliente;
		this.curso = curso;
		this.pedidoData = pedidoData;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clienteId", column = @Column(name = "cliente_id", nullable = false)),
			@AttributeOverride(name = "cursoId", column = @Column(name = "curso_id", nullable = false)) })
	public PedidoId getId() {
		return this.id;
	}

	public void setId(PedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curso_id", nullable = false, insertable = false, updatable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pedido_data", nullable = false, length = 10)
	public Date getPedidoData() {
		return this.pedidoData;
	}

	public void setPedidoData(Date pedidoData) {
		this.pedidoData = pedidoData;
	}

}
