package com.lojavirtual.model;
// Generated 7 de nov. de 2022 23:22:36 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "Curso", catalog = "lojavirtual")
public class Curso implements java.io.Serializable {

	private Integer cursoId;
	private String cursoNome;
	private String cursoDescricao;
	private double cursoValor;

	public Curso() {
	}

	public Curso(String cursoNome, String cursoDescricao, double cursoValor) {
		this.cursoNome = cursoNome;
		this.cursoDescricao = cursoDescricao;
		this.cursoValor = cursoValor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "curso_id", unique = true, nullable = false)
	public Integer getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(Integer cursoId) {
		this.cursoId = cursoId;
	}

	@Column(name = "curso_nome", nullable = false, length = 40)
	public String getCursoNome() {
		return this.cursoNome;
	}

	public void setCursoNome(String cursoNome) {
		this.cursoNome = cursoNome;
	}

	@Column(name = "curso_descricao", nullable = false, length = 80)
	public String getCursoDescricao() {
		return this.cursoDescricao;
	}

	public void setCursoDescricao(String cursoDescricao) {
		this.cursoDescricao = cursoDescricao;
	}

	@Column(name = "curso_valor", nullable = false, precision = 30)
	public double getCursoValor() {
		return this.cursoValor;
	}

	public void setCursoValor(double cursoValor) {
		this.cursoValor = cursoValor;
	}

}
