package com.curso4.unidade4.teste;
// Generated 3 de nov. de 2022 00:20:59 by Hibernate Tools 5.6.12.Final

import java.util.Date;

/**
 * ClienteHasCurso generated by hbm2java
 */
public class ClienteHasCurso implements java.io.Serializable {

	private ClienteHasCursoId id;
	private Cliente cliente;
	private Curso curso;
	private Date vendaData;

	public ClienteHasCurso() {
	}

	public ClienteHasCurso(ClienteHasCursoId id, Cliente cliente, Curso curso, Date vendaData) {
		this.id = id;
		this.cliente = cliente;
		this.curso = curso;
		this.vendaData = vendaData;
	}

	public ClienteHasCursoId getId() {
		return this.id;
	}

	public void setId(ClienteHasCursoId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public Date getVendaData() {
		return this.vendaData;
	}

	public void setVendaData(Date vendaData) {
		this.vendaData = vendaData;
	}

}
